name: valorant_universe_remastered
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'
dependencies:
  flutter:
    sdk: flutter

  #networking
  dio: ^4.0.6
  pretty_dio_logger: ^1.1.1
  internet_connection_checker: ^0.0.1+4

  #state management
  bloc: ^8.1.0
  flutter_bloc: ^8.1.1

  #routing
  auto_route: ^5.0.1

  #data class generation
  json_annotation: ^4.6.0
  freezed_annotation: ^2.1.0

  #functional programming
  dartz: ^0.10.1

  #ui
  cached_network_image: ^3.2.2
  salomon_bottom_bar: ^3.3.1
  lottie: ^1.4.2

  #app icons
  flutter_native_splash: ^2.2.9
  flutter_launcher_icons: ^0.10.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  
  #code gen
  freezed: ^2.1.0+1
  json_serializable: ^6.3.1
  auto_route_generator: ^5.0.2
  build_runner: ^2.2.0
  
  #linter
  flutter_lints: ^2.0.0

flutter_icons: 
  android: true
  ios: true
  image_path: "assets/icons/app_icon.png"
  adaptive_icon_background: "#000000"
  adaptive_icon_foreground: "assets/icons/app_icon_foreground.png"
  windows:
    generate: false
  web:
    generate: false


flutter_native_splash:
  android: true
  ios: true
  web: false
  color: "#000000"
  image: assets/icons/app_icon.png
  android12: true

flutter:

  uses-material-design: true

  assets:
    - assets/animations/loading_animation.json

  fonts:
    - family: Valorant
      fonts:
        - asset: assets/fonts/valorant_font.ttf

    - family: CustomIcons
      fonts:
        - asset: assets/icons/custom_icons.ttf

