name: valorant_universe_remastered
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter

  #networking
  dio: ^5.4.3+1
  dio_smart_retry: ^5.0.0
  pretty_dio_logger: ^1.3.1
  internet_connection_checker: ^1.0.0+1

  #state management
  flutter_bloc: ^8.1.6

  #routing
  auto_route: ^7.9.2

  #localization
  easy_localization: ^3.0.7

  #dependency injection
  get_it: ^7.7.0

  #data class generation
  json_annotation: ^4.9.0
  freezed_annotation: ^2.4.1

  #utility
  fpdart: ^1.1.0
  logger: ^2.3.0
  envied: ^0.3.0+3

  #ui
  lottie: ^2.7.0
  salomon_bottom_bar: ^3.3.2
  cached_network_image: ^3.3.1

  #app icons
  flutter_native_splash: ^2.4.0
  flutter_launcher_icons: ^0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  bloc_test: ^9.1.7

  #code gen
  freezed: ^2.5.2
  build_runner: ^2.4.11
  json_serializable: ^6.8.0
  envied_generator: ^0.3.0+3
  auto_route_generator: ^7.3.2

  #linter
  very_good_analysis: ^5.1.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/app_icon.png"
  adaptive_icon_background: "#000000"
  adaptive_icon_foreground: "assets/icons/app_icon_foreground.png"
  windows:
    generate: false
  web:
    generate: false

flutter_native_splash:
  android: true
  ios: true
  web: false
  color: "#000000"
  image: assets/icons/app_icon.png
  android12: true

flutter:
  uses-material-design: true

  assets:
    - assets/animations/
    - assets/translations/

  fonts:
    - family: Valorant
      fonts:
        - asset: assets/fonts/valorant_font.ttf

    - family: CustomIcons
      fonts:
        - asset: assets/icons/custom_icons.ttf
